version: '2'
services:
    loyalty-app:
        image: loyalty
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://loyalty-postgresql:5432/loyalty
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    loyalty-postgresql:
        extends:
            file: postgresql.yml
            service: loyalty-postgresql
